### ISSUE TITLE
Offline install fails on RHEL

### ISSUE THREAD

**Issue by just1victory** [canonical-web-and-design/microk8s.io#321]
Offline install of microk8s on RHEL 7.7 fails

## Process

https://microk8s.io/docs/install-alternatives#heading--offline

Current results:
sudo snap ack microk8s_1379.assert

sudo install microk8s_1379.snap
error: This revision of snap "microk8s_1379.snap" was published using classic confinement and thus may perform arbitrary system changes outside of the security sandbox that snaps are usually confined tom which may put your system at risk
If you understand and want to proceed repeat the command including --classic

sudo install microk8s.snap --classic
error: cannot perform the following tasks:
-Ensure prerequisites for "microk8s" are available (cannot install snap base "core": Post https://api.snapcraft.io/v2/snaps/refresh: dial tcp: lookup api.snapcraft.io on xx.xx.xx.xx:53: read tcp: xx.xx.xx.xx:35831->xx.xx.xx.xx:53: i/o timeout)

Help!

## Screenshot

[If relevant, include a screenshot.]

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by evilnick** [comment]
Thanks for reporting this. This is an omission from the docs, because it was written for offline install on Ubuntu (which already has the core snap). I will update the docs, but the short answer to your problem is to:
`sudo snap download core`
and follow the same procedure to install it, before installing MicroK8s.

Let me know if you have more problems

**Comment by evilnick** [comment]
This has now been updated on the docs
